"""pytest fixtures for psdparse tests.

Injects the built pybind11 module into sys.path and exposes the sample PSDs
in tests/data/ as fixtures.
"""
import os
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent

# Locate the most recent build of the psdparse Python module.
_CANDIDATES = [
    REPO / "build" / "x64-windows-python" / "python" / "Release",
    REPO / "build" / "x64-windows-python" / "python" / "Debug",
]
for _d in _CANDIDATES:
    if _d.is_dir() and any(_d.glob("psdparse*.pyd")):
        sys.path.insert(0, str(_d))
        break

# Allow override via env var (CI / custom build dirs).
_env_dir = os.environ.get("PSDPARSE_BUILD_DIR")
if _env_dir:
    sys.path.insert(0, _env_dir)

import psdparse  # noqa: E402  -- after sys.path setup


DATA = REPO / "tests" / "data"


def _find_sample(*names):
    """Return the first existing path among given basenames in tests/data/
    or the repo root (legacy location)."""
    for name in names:
        for root in (DATA, REPO):
            p = root / name
            if p.is_file():
                return p
    pytest.skip(f"sample PSD not found: {names!r}")


@pytest.fixture(scope="session")
def sample_ui_psd():
    return _find_sample("UI-PSDサンプル.psd", "UI-PSD-sample.psd")


@pytest.fixture(scope="session")
def sample_large_psd():
    return _find_sample("園部由夏_a.psd", "large.psd")


@pytest.fixture(scope="session")
def sample_text_psd():
    return _find_sample("fontsample.psd")


@pytest.fixture(scope="session")
def sample_group_psd():
    """A PSD with nested folder groups (for hierarchy / metadata tests)."""
    return _find_sample("config.psd", "system.psd")


@pytest.fixture(scope="session")
def sample_mask_psd():
    """A small PSD with a layer mask (synthesized fixture)."""
    return _find_sample("masktest.psd")


@pytest.fixture(scope="session")
def sample_maskparams_psd():
    """A PSD whose layer mask carries a real/user mask section plus mask
    parameters (density + feather) and an lclr color label (synthesized)."""
    return _find_sample("maskparams.psd")


@pytest.fixture(scope="session")
def sample_textbox_psd():
    """Two text layers (one horizontal, one vertical) with several fonts,
    sizes and per-paragraph alignments — the fixture for rich-text,
    justification and text placement / box editing."""
    return _find_sample("textboxsample.psd")


@pytest.fixture(scope="session")
def sample_textmask_psd():
    """textboxsample.psd with a layer mask added to both text layers
    (generated by tests/data/make_textmask.py). Text layer + mask is the
    combination that shows up when a PSD carries one text layer per language,
    so duplication and text edits have to keep the mask intact."""
    return _find_sample("textmask.psd")


@pytest.fixture(scope="session")
def sample_layercomps_psd():
    """A PSD with Photoshop layer comps (Adobe's 'Layer Comps.psd' sample,
    saved locally as layercomps.psd; not committed)."""
    return _find_sample("layercomps.psd", "Layer Comps.psd")


@pytest.fixture(scope="session")
def sample_lab_psd():
    """A Lab-mode PSD with known swatches (synthesized)."""
    return _find_sample("labsample.psd")


@pytest.fixture(scope="session")
def sample_gray_psd():
    """A grayscale PSD (synthesized)."""
    return _find_sample("graysample.psd")


@pytest.fixture(scope="session")
def sample_duo_psd():
    """The grayscale PSD with its color mode flipped to Duotone (synthesized)."""
    return _find_sample("duosample.psd")


@pytest.fixture
def psd_ui(sample_ui_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_ui_psd))
    return p


@pytest.fixture
def psd_text(sample_text_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_text_psd))
    return p


@pytest.fixture
def psd_group(sample_group_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_group_psd))
    return p


@pytest.fixture
def psd_mask(sample_mask_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_mask_psd))
    return p


@pytest.fixture
def psd_maskparams(sample_maskparams_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_maskparams_psd))
    return p


@pytest.fixture
def psd_textbox(sample_textbox_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_textbox_psd))
    return p


@pytest.fixture
def psd_textmask(sample_textmask_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_textmask_psd))
    return p


@pytest.fixture
def psd_layercomps(sample_layercomps_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_layercomps_psd))
    return p


@pytest.fixture
def psd_lab(sample_lab_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_lab_psd))
    return p


@pytest.fixture
def psd_gray(sample_gray_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_gray_psd))
    return p


@pytest.fixture
def psd_duo(sample_duo_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_duo_psd))
    return p


@pytest.fixture
def psd_large(sample_large_psd):
    p = psdparse.PSDFile()
    assert p.load(str(sample_large_psd))
    return p
